spring.application.name=user-authentication-api

projeto.jwtSecret=r9F3vV0w3DkK8s5Qx7JtP2mA6YhLzWcE1uN4iR8bXcQ9dF6sG2hJkL5pT7vB3nZxQ8mC1aD0wE9rU6yP4oT2bH5V8kN1sM3L
# chave caso essa dê erro //VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9ySFNBNTEyQW5kTXVzdEJlTG9uZ0Vub3VnaA==
projeto.jwtExpirationMs=900000
